<?php

namespace tests\unit\routing;

use Codeception\Test\Unit;
use Yii;
use yii\helpers\Url;

/**
 * Property-based tests for AJAX URL generation
 * 
 * **Feature: yiimp2-admin-panel-fixes, Property 9: AJAX URLs match route patterns**
 * **Validates: Requirements 6.2**
 */
class AjaxUrlPropertyTest extends Unit
{
    /**
     * @var \UnitTester
     */
    protected $tester;

    protected function _before()
    {
        parent::_before();
        // Ensure URL manager is properly configured
        Yii::$app->urlManager->enablePrettyUrl = true;
        Yii::$app->urlManager->showScriptName = false;
    }

    /**
     * Property 9: AJAX URLs match route patterns
     * 
     * For any AJAX request generated by a view, the URL should follow the hyphenated
     * convention and successfully reach the intended controller action.
     * 
     * This test verifies that:
     * 1. AJAX URLs are generated using Url::to() helper
     * 2. Generated URLs use hyphens instead of underscores
     * 3. URLs match the configured route patterns
     * 4. URLs are properly formatted for AJAX requests
     * 
     * @dataProvider ajaxEndpointProvider
     */
    public function testAjaxUrlsMatchRoutePatterns($controller, $action, $expectedPattern)
    {
        // Generate AJAX URL using URL manager
        $route = $controller . '/' . $action;
        $urlManager = Yii::$app->urlManager;
        $generatedUrl = $urlManager->createAbsoluteUrl([$route]);
        
        // Verify the URL was generated
        $this->assertNotEmpty($generatedUrl, 
            "URL should be generated for route: {$route}");
        
        // Verify no underscores in the URL path
        $urlPath = parse_url($generatedUrl, PHP_URL_PATH);
        $this->assertStringNotContainsString('_', $urlPath,
            "AJAX URL should not contain underscores: {$generatedUrl}");
        
        // Verify the URL matches the expected pattern
        $this->assertStringContainsString($expectedPattern, $generatedUrl,
            "AJAX URL should match pattern '{$expectedPattern}': {$generatedUrl}");
        
        // Verify the URL contains the expected pattern (may have test environment prefix)
        $this->assertStringContainsString($expectedPattern, $generatedUrl,
            "AJAX URL should contain expected pattern: {$generatedUrl}");
    }

    /**
     * Data provider for AJAX endpoints
     * 
     * Returns controller, action, and expected URL pattern
     */
    public function ajaxEndpointProvider()
    {
        return [
            // Admin user management
            ['admin', 'user-results', 'admin/user-results'],
            
            // Admin worker monitoring
            ['admin', 'worker-results', 'admin/worker-results'],
            
            // Admin payment monitoring
            ['admin', 'payments-results', 'admin/payments-results'],
            
            // Admin earning monitoring
            ['admin', 'earning-results', 'admin/earning-results'],
            
            // Admin exchange management
            ['admin', 'exchange-results', 'admin/exchange-results'],
            ['admin', 'balances-results', 'admin/balances-results'],
            
            // Admin connection monitoring
            ['admin', 'connections-results', 'admin/connections-results'],
            
            // Admin dashboard
            ['admin', 'dashboard-results', 'admin/dashboard-results'],
            
            // Admin version monitoring
            ['admin', 'version-results', 'admin/version-results'],
            
            // Site miners page
            ['site', 'miners-results', 'site/miners-results'],
        ];
    }

    /**
     * Test AJAX URL generation with query parameters
     * 
     * Verifies that AJAX URLs with parameters are properly formatted
     * 
     * @dataProvider ajaxUrlWithParamsProvider
     */
    public function testAjaxUrlsWithQueryParameters($route, $params, $expectedKeys)
    {
        // Generate URL with parameters
        $urlManager = Yii::$app->urlManager;
        $generatedUrl = $urlManager->createAbsoluteUrl(array_merge([$route], $params));
        
        // Verify URL was generated
        $this->assertNotEmpty($generatedUrl,
            "URL should be generated for route with params: {$route}");
        
        // Parse URL to check query string
        $urlParts = parse_url($generatedUrl);
        
        // Verify no underscores in the path
        if (isset($urlParts['path'])) {
            $this->assertStringNotContainsString('_', $urlParts['path'],
                "URL path should not contain underscores: {$generatedUrl}");
        }
        
        // Verify query parameters are present
        if (!empty($params) && isset($urlParts['query'])) {
            parse_str($urlParts['query'], $queryParams);
            
            foreach ($expectedKeys as $key) {
                $this->assertArrayHasKey($key, $queryParams,
                    "Query parameters should include '{$key}': {$generatedUrl}");
            }
        }
    }

    /**
     * Data provider for AJAX URLs with parameters
     */
    public function ajaxUrlWithParamsProvider()
    {
        return [
            // User search with filters
            [
                'admin/user-results',
                ['search' => 'test', 'coinid' => '1'],
                ['search', 'coinid']
            ],
            
            // Worker filtering
            [
                'admin/worker-results',
                ['algo' => 'sha256', 'active' => '1'],
                ['algo', 'active']
            ],
            
            // Payment filtering
            [
                'admin/payments-results',
                ['status' => 'pending', 'coinid' => '2'],
                ['status', 'coinid']
            ],
            
            // Earning filtering
            [
                'admin/earning-results',
                ['coinid' => '1', 'algo' => 'scrypt'],
                ['coinid', 'algo']
            ],
        ];
    }

    /**
     * Test that AJAX URLs are consistent with view usage
     * 
     * Simulates how views generate AJAX URLs and verifies consistency
     */
    public function testAjaxUrlConsistencyWithViewUsage()
    {
        $testCases = [
            ['admin/user-results', []],
            ['admin/worker-results', ['algo' => 'sha256']],
            ['admin/payments-results', ['status' => 'pending']],
        ];

        $urlManager = Yii::$app->urlManager;
        foreach ($testCases as list($route, $params)) {
            // Generate URL as a view would
            $url1 = $urlManager->createAbsoluteUrl(array_merge([$route], $params));
            
            // Generate again to verify consistency
            $url2 = $urlManager->createAbsoluteUrl(array_merge([$route], $params));
            
            $this->assertEquals($url1, $url2,
                "AJAX URL generation should be consistent for route: {$route}");
            
            // Verify hyphenated format
            $urlPath = parse_url($url1, PHP_URL_PATH);
            $this->assertStringNotContainsString('_', $urlPath,
                "AJAX URL should use hyphens: {$url1}");
        }
    }

    /**
     * Test AJAX URL generation for all admin result endpoints
     * 
     * Verifies that all *-results endpoints generate valid URLs
     * 
     * @dataProvider adminResultEndpointProvider
     */
    public function testAllAdminResultEndpointsGenerateValidUrls($endpoint)
    {
        $urlManager = Yii::$app->urlManager;
        $url = $urlManager->createAbsoluteUrl(['admin/' . $endpoint]);
        
        // Verify URL is generated
        $this->assertNotEmpty($url,
            "URL should be generated for endpoint: {$endpoint}");
        
        // Verify no underscores
        $urlPath = parse_url($url, PHP_URL_PATH);
        $this->assertStringNotContainsString('_', $urlPath,
            "Endpoint URL should not contain underscores: {$url}");
        
        // Verify it ends with -results
        $this->assertStringEndsWith('-results', $endpoint,
            "Result endpoint should end with '-results': {$endpoint}");
        
        // Verify the URL contains the endpoint
        $this->assertStringContainsString($endpoint, $url,
            "URL should contain the endpoint name: {$url}");
    }

    /**
     * Data provider for admin result endpoints
     */
    public function adminResultEndpointProvider()
    {
        return [
            ['user-results'],
            ['worker-results'],
            ['payments-results'],
            ['earning-results'],
            ['exchange-results'],
            ['balances-results'],
            ['connections-results'],
            ['dashboard-results'],
            ['version-results'],
        ];
    }

    /**
     * Test that AJAX URLs work with relative and absolute formats
     */
    public function testAjaxUrlsWorkWithDifferentFormats()
    {
        $route = 'admin/user-results';
        $urlManager = Yii::$app->urlManager;
        
        // Test absolute URL generation
        $absoluteUrl = $urlManager->createAbsoluteUrl([$route]);
        $this->assertNotEmpty($absoluteUrl);
        
        // Verify no underscores in path
        $absolutePath = parse_url($absoluteUrl, PHP_URL_PATH);
        if ($absolutePath) {
            $this->assertStringNotContainsString('_', $absolutePath,
                "Absolute URL path should not contain underscores");
        }
        
        // Verify the route is in the URL
        $this->assertStringContainsString('user-results', $absoluteUrl,
            "URL should contain the hyphenated action name");
    }

    /**
     * Test AJAX URL generation matches configured routes
     * 
     * Verifies that generated URLs align with urlManager rules
     */
    public function testAjaxUrlsMatchConfiguredRoutes()
    {
        $urlManager = Yii::$app->urlManager;
        
        // Get configured rules
        $rules = $urlManager->rules;
        
        // Test that admin routes follow the pattern
        $adminRoutes = [
            'admin/user-results',
            'admin/worker-results',
            'admin/payments-results',
        ];

        foreach ($adminRoutes as $route) {
            $url = $urlManager->createAbsoluteUrl([$route]);
            
            // Verify URL follows admin/<action> pattern
            $this->assertMatchesRegularExpression(
                '#/admin/[a-z-]+#',
                $url,
                "Admin AJAX URL should follow admin/<action> pattern: {$url}"
            );
            
            // Verify no underscores
            $this->assertDoesNotMatchRegularExpression(
                '#_#',
                parse_url($url, PHP_URL_PATH),
                "Admin AJAX URL should not contain underscores: {$url}"
            );
        }
    }

    /**
     * Test that AJAX URLs handle special characters properly
     */
    public function testAjaxUrlsHandleSpecialCharactersInParameters()
    {
        $route = 'admin/user-results';
        $specialParams = [
            'search' => 'test@example.com',
            'filter' => 'value with spaces',
        ];

        $urlManager = Yii::$app->urlManager;
        $url = $urlManager->createAbsoluteUrl(array_merge([$route], $specialParams));
        
        // Verify URL is generated
        $this->assertNotEmpty($url);
        
        // Verify path doesn't contain underscores
        $urlPath = parse_url($url, PHP_URL_PATH);
        $this->assertStringNotContainsString('_', $urlPath);
        
        // Verify query string is properly encoded
        $urlParts = parse_url($url);
        if (isset($urlParts['query'])) {
            parse_str($urlParts['query'], $queryParams);
            
            // Verify parameters are preserved
            $this->assertArrayHasKey('search', $queryParams);
            $this->assertArrayHasKey('filter', $queryParams);
        }
    }
}
