<?php

namespace tests\unit\security;

use Codeception\Test\Unit;
use Yii;

/**
 * Property-based test for session CSRF token storage
 * 
 * Feature: csrf-session-management-fix, Property 1: Session CSRF Token Storage
 * Validates: Requirements 1.1, 1.2, 1.3
 * 
 * Property: For any user session initialization, the system should generate a CSRF token
 * and store it in the session storage, and subsequent queries should return a non-null token value.
 */
class SessionCsrfTokenStoragePropertyTest extends Unit
{
    /**
     * @var \UnitTester
     */
    protected $tester;
    
    /**
     * Property 1: Session CSRF Token Storage
     * 
     * For any user session initialization, the system should:
     * 1. Generate a CSRF token (Requirement 1.1)
     * 2. Store it in session storage (Requirement 1.2)
     * 3. Return a non-null value when queried (Requirement 1.3)
     * 
     * This property must hold across all possible session initializations.
     * 
     * Feature: csrf-session-management-fix, Property 1: Session CSRF Token Storage
     * Validates: Requirements 1.1, 1.2, 1.3
     * 
     * @test
     */
    public function testSessionCsrfTokenStorageProperty()
    {
        // Feature: csrf-session-management-fix, Property 1: Session CSRF Token Storage
        
        $iterations = 100;
        $failures = [];
        
        for ($i = 0; $i < $iterations; $i++) {
            // Destroy any existing session to start fresh
            if (Yii::$app->session->getIsActive()) {
                Yii::$app->session->destroy();
            }
            
            // Initialize session (simulates user accessing the application)
            try {
                Yii::$app->session->open();
            } catch (\Exception $e) {
                $failures[] = [
                    'iteration' => $i,
                    'phase' => 'session_initialization',
                    'reason' => 'Failed to open session',
                    'error' => $e->getMessage(),
                ];
                continue;
            }
            
            // Property Check 1: CSRF token should be generated (Requirement 1.1)
            try {
                $csrfToken = Yii::$app->request->getCsrfToken();
            } catch (\Exception $e) {
                $failures[] = [
                    'iteration' => $i,
                    'phase' => 'token_generation',
                    'reason' => 'Failed to generate CSRF token',
                    'error' => $e->getMessage(),
                ];
                continue;
            }
            
            if (empty($csrfToken)) {
                $failures[] = [
                    'iteration' => $i,
                    'phase' => 'token_generation',
                    'reason' => 'CSRF token is empty',
                    'token' => $csrfToken,
                ];
                continue;
            }
            
            if (!is_string($csrfToken)) {
                $failures[] = [
                    'iteration' => $i,
                    'phase' => 'token_generation',
                    'reason' => 'CSRF token is not a string',
                    'token_type' => gettype($csrfToken),
                ];
                continue;
            }
            
            // Verify token has sufficient length (security requirement)
            if (strlen($csrfToken) < 10) {
                $failures[] = [
                    'iteration' => $i,
                    'phase' => 'token_generation',
                    'reason' => 'CSRF token is too short (security issue)',
                    'token_length' => strlen($csrfToken),
                    'token' => $csrfToken,
                ];
                continue;
            }
            
            // Property Check 2: Token should be stored in session (Requirement 1.2)
            // Note: Yii2 stores the CSRF token in session automatically when getCsrfToken() is called
            // The token is stored under the csrfParam key
            $csrfParam = Yii::$app->request->csrfParam;
            
            // In Yii2, the CSRF token storage works as follows:
            // 1. getCsrfToken() generates a masked token
            // 2. The base token is stored in session
            // 3. The masked token is returned to the client
            //
            // The key insight is that Yii2 uses loadCsrfToken() internally which:
            // - First checks cookies for the token
            // - Then checks session for the token
            // - If neither exists, generates a new one and stores it
            //
            // So we need to verify that after calling getCsrfToken(), the token
            // is accessible from session storage.
            
            // Force the token to be loaded/generated by accessing it
            // This should trigger storage in session
            $tokenFromRequest = Yii::$app->request->getCsrfToken();
            
            // Now check if it's in session
            // Note: Yii2 might store it under a different key or use cookies
            // Let's check both the session and verify the token is retrievable
            $sessionToken = Yii::$app->session->get($csrfParam);
            
            // If session token is null, it might be using cookie storage
            // or there's a configuration issue
            if ($sessionToken === null) {
                // Check if enableCsrfCookie is enabled (which would use cookies instead)
                $useCookie = Yii::$app->request->enableCsrfCookie;
                
                if (!$useCookie) {
                    // Session storage should be used, but token is not there
                    // Get all session keys for debugging
                    $sessionKeys = [];
                    foreach (Yii::$app->session as $key => $value) {
                        $sessionKeys[] = $key;
                    }
                    
                    $failures[] = [
                        'iteration' => $i,
                        'phase' => 'token_storage',
                        'reason' => 'CSRF token not stored in session (cookie mode disabled)',
                        'csrf_param' => $csrfParam,
                        'session_keys' => $sessionKeys,
                        'enable_csrf_cookie' => $useCookie,
                        'token_generated' => !empty($tokenFromRequest),
                    ];
                    continue;
                }
                // If using cookies, that's acceptable - the token is still stored
                // We'll verify it's retrievable in the next check
            }
            
            // Property Check 3: Subsequent queries should return non-null value (Requirement 1.3)
            try {
                $retrievedToken = Yii::$app->request->getCsrfToken();
            } catch (\Exception $e) {
                $failures[] = [
                    'iteration' => $i,
                    'phase' => 'token_retrieval',
                    'reason' => 'Failed to retrieve CSRF token',
                    'error' => $e->getMessage(),
                ];
                continue;
            }
            
            if ($retrievedToken === null) {
                $failures[] = [
                    'iteration' => $i,
                    'phase' => 'token_retrieval',
                    'reason' => 'Retrieved CSRF token is null',
                ];
                continue;
            }
            
            if (empty($retrievedToken)) {
                $failures[] = [
                    'iteration' => $i,
                    'phase' => 'token_retrieval',
                    'reason' => 'Retrieved CSRF token is empty',
                    'token' => $retrievedToken,
                ];
                continue;
            }
            
            // Additional check: Multiple retrievals should return consistent token
            $secondRetrieval = Yii::$app->request->getCsrfToken();
            if ($retrievedToken !== $secondRetrieval) {
                $failures[] = [
                    'iteration' => $i,
                    'phase' => 'token_consistency',
                    'reason' => 'Multiple retrievals return different tokens',
                    'first_token' => $retrievedToken,
                    'second_token' => $secondRetrieval,
                ];
            }
            
            // Clean up session for next iteration
            Yii::$app->session->close();
        }
        
        // Report failures if any
        if (!empty($failures)) {
            $failureCount = count($failures);
            $failuresByPhase = [];
            foreach ($failures as $failure) {
                $phase = $failure['phase'] ?? 'unknown';
                if (!isset($failuresByPhase[$phase])) {
                    $failuresByPhase[$phase] = 0;
                }
                $failuresByPhase[$phase]++;
            }
            
            $this->fail(
                "Property 1 (Session CSRF Token Storage) failed in $failureCount out of $iterations iterations.\n" .
                "Failures by phase: " . json_encode($failuresByPhase, JSON_PRETTY_PRINT) . "\n" .
                "First 5 failures:\n" . json_encode(array_slice($failures, 0, 5), JSON_PRETTY_PRINT)
            );
        }
        
        $this->assertTrue(
            true,
            "Property 1 holds for all $iterations iterations: " .
            "CSRF tokens are properly generated, stored in session, and retrievable"
        );
    }
    
    /**
     * Generate random session configuration for property testing
     * 
     * This creates diverse session configurations to test the property
     * across different scenarios.
     * 
     * @return array Session configuration
     */
    protected function generateRandomSessionConfig()
    {
        $configs = [
            // Standard CacheSession configuration (production-like)
            [
                'class' => 'yii\web\CacheSession',
                'cache' => 'cache',
                'name' => 'YIIMP2SESSID_' . rand(1000, 9999),
                'timeout' => rand(1800, 7200),
                'useCookies' => true,
                'cookieParams' => [
                    'httponly' => true,
                    'secure' => (bool)rand(0, 1),
                    'sameSite' => rand(0, 1) ? 'Lax' : null,
                ],
            ],
            // File-based session (fallback scenario)
            [
                'class' => 'yii\web\Session',
                'name' => 'YIIMP2SESSID_' . rand(1000, 9999),
                'timeout' => rand(1800, 7200),
                'useCookies' => true,
                'cookieParams' => [
                    'httponly' => true,
                ],
            ],
            // Minimal configuration
            [
                'class' => 'yii\web\Session',
                'name' => 'TEST_' . rand(1000, 9999),
            ],
        ];
        
        return $configs[array_rand($configs)];
    }
    
    /**
     * Test that CSRF token persists across multiple requests in same session
     * 
     * This verifies that the token remains consistent within a session,
     * which is critical for form submissions.
     * 
     * @test
     */
    public function testCsrfTokenPersistenceInSession()
    {
        $iterations = 50;
        $failures = [];
        
        for ($i = 0; $i < $iterations; $i++) {
            // Start fresh session
            if (Yii::$app->session->getIsActive()) {
                Yii::$app->session->destroy();
            }
            
            Yii::$app->session->open();
            
            // Get initial token
            $initialToken = Yii::$app->request->getCsrfToken();
            
            // Simulate multiple requests in same session
            $requestCount = rand(3, 10);
            $tokens = [$initialToken];
            
            for ($j = 0; $j < $requestCount; $j++) {
                $token = Yii::$app->request->getCsrfToken();
                $tokens[] = $token;
                
                // Verify token is not null
                if ($token === null || empty($token)) {
                    $failures[] = [
                        'iteration' => $i,
                        'request' => $j,
                        'reason' => 'Token became null/empty during session',
                    ];
                }
            }
            
            // Verify all tokens are the same (consistency within session)
            $uniqueTokens = array_unique($tokens);
            if (count($uniqueTokens) !== 1) {
                $failures[] = [
                    'iteration' => $i,
                    'reason' => 'Token changed within same session',
                    'unique_token_count' => count($uniqueTokens),
                    'request_count' => $requestCount + 1,
                ];
            }
            
            Yii::$app->session->close();
        }
        
        if (!empty($failures)) {
            $this->fail(
                "Token persistence test failed in " . count($failures) . " out of $iterations iterations:\n" .
                json_encode(array_slice($failures, 0, 5), JSON_PRETTY_PRINT)
            );
        }
        
        $this->assertTrue(true, "CSRF token persists correctly across requests in all $iterations sessions");
    }
    
    /**
     * Test CSRF token storage with different session backends
     * 
     * Verifies that token storage works correctly regardless of session backend
     * (CacheSession, FileSession, etc.)
     * 
     * @test
     */
    public function testCsrfTokenStorageAcrossSessionBackends()
    {
        $backends = [
            'CacheSession' => [
                'class' => 'yii\web\CacheSession',
                'cache' => 'cache',
            ],
            'FileSession' => [
                'class' => 'yii\web\Session',
            ],
        ];
        
        $failures = [];
        $iterationsPerBackend = 25;
        
        foreach ($backends as $backendName => $config) {
            for ($i = 0; $i < $iterationsPerBackend; $i++) {
                // Configure session backend
                if (Yii::$app->session->getIsActive()) {
                    Yii::$app->session->destroy();
                }
                
                $config['name'] = 'TEST_' . rand(1000, 9999);
                $config['timeout'] = 3600;
                
                Yii::$app->set('session', $config);
                
                try {
                    Yii::$app->session->open();
                    
                    // Generate and verify token
                    $token = Yii::$app->request->getCsrfToken();
                    
                    if (empty($token)) {
                        $failures[] = [
                            'backend' => $backendName,
                            'iteration' => $i,
                            'reason' => 'Failed to generate token',
                        ];
                        continue;
                    }
                    
                    // Verify token can be retrieved again (which proves it's stored)
                    $retrievedToken = Yii::$app->request->getCsrfToken();
                    
                    if (empty($retrievedToken)) {
                        $failures[] = [
                            'backend' => $backendName,
                            'iteration' => $i,
                            'reason' => 'Failed to retrieve token from storage',
                        ];
                        continue;
                    }
                    
                    // Verify tokens are consistent (proves storage is working)
                    if ($token !== $retrievedToken) {
                        $failures[] = [
                            'backend' => $backendName,
                            'iteration' => $i,
                            'reason' => 'Token inconsistency indicates storage issue',
                            'original' => substr($token, 0, 20) . '...',
                            'retrieved' => substr($retrievedToken, 0, 20) . '...',
                        ];
                    }
                    
                    Yii::$app->session->close();
                } catch (\Exception $e) {
                    $failures[] = [
                        'backend' => $backendName,
                        'iteration' => $i,
                        'reason' => 'Exception during test',
                        'error' => $e->getMessage(),
                    ];
                }
            }
        }
        
        if (!empty($failures)) {
            $failuresByBackend = [];
            foreach ($failures as $failure) {
                $backend = $failure['backend'];
                if (!isset($failuresByBackend[$backend])) {
                    $failuresByBackend[$backend] = 0;
                }
                $failuresByBackend[$backend]++;
            }
            
            $this->fail(
                "Backend compatibility test failed in " . count($failures) . " iterations:\n" .
                "Failures by backend: " . json_encode($failuresByBackend, JSON_PRETTY_PRINT) . "\n" .
                "Sample failures:\n" . json_encode(array_slice($failures, 0, 3), JSON_PRETTY_PRINT)
            );
        }
        
        $totalIterations = count($backends) * $iterationsPerBackend;
        $this->assertTrue(
            true,
            "CSRF token storage works correctly across all backends in $totalIterations iterations"
        );
    }
}
