[TCP]
server = 0.0.0.0
port = 3333
password = yiimp2_stratum_password

[SQL]
host = yiimp2-db
database = yiimp2
username = yiimp2
password = YIIMP2_DB_PASSWORD

[STRATUM]
algo = x13
difficulty = 128
max_ttf = 40000
