<?php

namespace app\components;

use Yii;
use yii\base\Component;

/**
 * CSP Nonce Manager
 * 
 * Generates and manages Content Security Policy nonces for inline scripts and styles.
 * This allows strict CSP policies without 'unsafe-inline' or 'unsafe-eval'.
 */
class CspNonceManager extends Component
{
    /**
     * @var string The nonce value for the current request
     */
    private $_nonce;

    /**
     * Get the nonce for the current request
     * 
     * The nonce is generated by Nginx and passed via HTTP_X_CSP_NONCE header.
     * If not available (e.g., in tests or non-Nginx environments), generates a fallback nonce.
     * 
     * @return string The nonce value
     */
    public function getNonce()
    {
        if ($this->_nonce === null) {
            // Try to get nonce from Nginx (passed via fastcgi_param)
            if (isset($_SERVER['HTTP_X_CSP_NONCE']) && !empty($_SERVER['HTTP_X_CSP_NONCE'])) {
                $this->_nonce = $_SERVER['HTTP_X_CSP_NONCE'];
            } else {
                // Fallback: generate nonce in PHP (for tests or non-Nginx environments)
                $this->_nonce = base64_encode(random_bytes(16));
            }
        }
        return $this->_nonce;
    }

    /**
     * Get the CSP script-src directive with nonce
     * 
     * @param bool $allowEval Whether to allow eval (for debug mode)
     * @return string The script-src directive
     */
    public function getScriptSrc($allowEval = false)
    {
        $nonce = $this->getNonce();
        $directive = "'self' 'nonce-{$nonce}'";
        
        if ($allowEval) {
            $directive .= " 'unsafe-eval'";
        }
        
        return $directive;
    }

    /**
     * Get the CSP style-src directive
     * 
     * Note: No nonce needed for styles as all inline styles have been removed.
     * All styling is done via external stylesheets loaded from 'self'.
     * 
     * @return string The style-src directive
     */
    public function getStyleSrc()
    {
        return "'self'";
    }

    /**
     * Get the full CSP header value
     * 
     * @param bool $isDev Whether in development mode
     * @return string The complete CSP header value
     */
    public function getCspHeader($isDev = false)
    {
        $scriptSrc = $this->getScriptSrc($isDev);
        $styleSrc = $this->getStyleSrc();
        
        $policy = "default-src 'self'; " .
                  "script-src {$scriptSrc}; " .
                  "style-src {$styleSrc}; " .
                  "img-src 'self' data:; " .
                  "font-src 'self' data:; " .
                  "connect-src 'self'; " .
                  "frame-ancestors 'none'; " .
                  "base-uri 'self'; " .
                  "form-action 'self'";
        
        return $policy;
    }

    /**
     * Get nonce attribute for inline script/style tags
     * 
     * @return string The nonce attribute (e.g., 'nonce="abc123"')
     */
    public function getNonceAttribute()
    {
        return 'nonce="' . $this->getNonce() . '"';
    }
}
