<?php

namespace tests\unit\components;

use Codeception\Test\Unit;
use app\components\DynamicStyleManager;
use app\components\YiimpUtils;

/**
 * Property-based tests for DynamicStyleManager component
 * 
 * Feature: csp-inline-styles-removal, Property 4: Dynamic style correctness
 * Validates: Requirements 2.5
 */
class DynamicStyleManagerPropertyTest extends Unit
{
    protected function _before()
    {
        parent::_before();
    }
    
    protected function _after()
    {
        parent::_after();
    }
    
    /**
     * Property 4: Dynamic style correctness
     * 
     * For any algorithm color value generated by PHP, the corresponding CSS class 
     * should apply the same background color.
     * 
     * Validates: Requirements 2.5
     * 
     * @test
     */
    public function testDynamicStyleCorrectness()
    {
        // Feature: csp-inline-styles-removal, Property 4: Dynamic style correctness
        
        $iterations = 100;
        $failures = [];
        
        for ($i = 0; $i < $iterations; $i++) {
            try {
                // Generate random algorithm data
                $algos = $this->generateRandomAlgos();
                
                if (empty($algos)) {
                    continue; // Skip empty iterations
                }
                
                // Generate CSS variables using DynamicStyleManager
                $cssVars = DynamicStyleManager::generateAlgoColorVars($algos);
                
                // Build a map of sanitized names to their last color (to handle duplicates)
                $sanitizedMap = [];
                foreach ($algos as $algo) {
                    if (!isset($algo['name']) || !isset($algo['color'])) {
                        continue;
                    }
                    
                    $className = DynamicStyleManager::getAlgoColorClass($algo['name']);
                    $sanitizedName = substr($className, strlen('algo-bg-'));
                    
                    // Store the last color for this sanitized name (duplicates overwrite)
                    $sanitizedMap[$sanitizedName] = [
                        'originalName' => $algo['name'],
                        'color' => $algo['color']
                    ];
                }
                
                // For each unique sanitized algorithm, verify the CSS variable matches the expected color
                foreach ($sanitizedMap as $sanitizedName => $data) {
                    $algoName = $data['originalName'];
                    $originalColor = $data['color'];
                    
                    // Verify the CSS variable is present in the generated CSS
                    $expectedVar = "--algo-color-{$sanitizedName}:";
                    if (strpos($cssVars, $expectedVar) === false) {
                        $failures[] = [
                            'iteration' => $i,
                            'algo' => $algoName,
                            'reason' => 'CSS variable not found in generated CSS',
                            'expectedVar' => $expectedVar,
                            'cssVars' => substr($cssVars, 0, 200)
                        ];
                        continue;
                    }
                    
                    // Extract the color value from the CSS variables
                    $pattern = "/--algo-color-{$sanitizedName}:\s*([^;]+);/";
                    if (preg_match($pattern, $cssVars, $matches)) {
                        $generatedColor = trim($matches[1]);
                        
                        // Validate the color format
                        if (!preg_match('/^#([A-Fa-f0-9]{3}|[A-Fa-f0-9]{6})$/', $originalColor)) {
                            // Original color is invalid, should use fallback
                            if ($generatedColor !== '#cccccc') {
                                $failures[] = [
                                    'iteration' => $i,
                                    'algo' => $algoName,
                                    'reason' => 'Invalid color should use fallback',
                                    'originalColor' => $originalColor,
                                    'generatedColor' => $generatedColor,
                                    'expectedFallback' => '#cccccc'
                                ];
                            }
                        } else {
                            // Original color is valid, should match exactly
                            if (strtolower($generatedColor) !== strtolower($originalColor)) {
                                $failures[] = [
                                    'iteration' => $i,
                                    'algo' => $algoName,
                                    'reason' => 'Generated color does not match original',
                                    'originalColor' => $originalColor,
                                    'generatedColor' => $generatedColor
                                ];
                            }
                        }
                    } else {
                        $failures[] = [
                            'iteration' => $i,
                            'algo' => $algoName,
                            'reason' => 'Could not extract color from CSS variables',
                            'pattern' => $pattern,
                            'cssVars' => substr($cssVars, 0, 200)
                        ];
                    }
                }
                
                // Test renderDynamicStyles generates valid HTML
                $config = ['algos' => $algos];
                $styleTag = DynamicStyleManager::renderDynamicStyles($config);
                
                if (!empty($sanitizedMap)) {
                    // Should generate a style tag when there are valid algos with colors
                    if (strpos($styleTag, '<style>') === false || strpos($styleTag, '</style>') === false) {
                        $failures[] = [
                            'iteration' => $i,
                            'reason' => 'renderDynamicStyles did not generate valid style tag',
                            'output' => substr($styleTag, 0, 200),
                            'algoCount' => count($sanitizedMap)
                        ];
                    }
                    
                    // Should contain :root selector
                    if (strpos($styleTag, ':root {') === false) {
                        $failures[] = [
                            'iteration' => $i,
                            'reason' => 'Style tag missing :root selector',
                            'output' => substr($styleTag, 0, 200)
                        ];
                    }
                    
                    // Should contain all unique algorithm colors
                    foreach ($sanitizedMap as $sanitizedName => $data) {
                        $expectedVar = "--algo-color-{$sanitizedName}";
                        
                        if (strpos($styleTag, $expectedVar) === false) {
                            $failures[] = [
                                'iteration' => $i,
                                'algo' => $data['originalName'],
                                'reason' => 'Algorithm color missing from style tag',
                                'expectedVar' => $expectedVar
                            ];
                        }
                    }
                }
                
            } catch (\Exception $e) {
                $failures[] = [
                    'iteration' => $i,
                    'reason' => 'Test execution failed',
                    'message' => $e->getMessage(),
                    'trace' => $e->getTraceAsString()
                ];
            }
        }
        
        // Report failures if any
        if (!empty($failures)) {
            $this->fail(
                "Property test failed in " . count($failures) . " out of $iterations iterations:\n" .
                json_encode($failures, JSON_PRETTY_PRINT)
            );
        }
        
        $this->assertTrue(true, "Property holds for all $iterations iterations");
    }
    
    /**
     * Generate random algorithm data for testing
     * 
     * @return array
     */
    protected function generateRandomAlgos()
    {
        $algoCount = rand(0, 10);
        $algos = [];
        $usedSanitizedNames = []; // Track sanitized names to avoid duplicates
        
        for ($i = 0; $i < $algoCount; $i++) {
            $algo = [];
            
            // Randomly decide whether to include name and color
            if (rand(0, 10) > 1) { // 90% chance to include name
                $algoName = $this->generateRandomAlgoName();
                
                // Get sanitized name to check for duplicates
                $className = DynamicStyleManager::getAlgoColorClass($algoName);
                $sanitizedName = substr($className, strlen('algo-bg-'));
                
                // Ensure unique sanitized algorithm names to avoid conflicts
                $attempts = 0;
                while (in_array($sanitizedName, $usedSanitizedNames) && $attempts < 10) {
                    $algoName = $this->generateRandomAlgoName();
                    $className = DynamicStyleManager::getAlgoColorClass($algoName);
                    $sanitizedName = substr($className, strlen('algo-bg-'));
                    $attempts++;
                }
                
                if (!in_array($sanitizedName, $usedSanitizedNames)) {
                    $algo['name'] = $algoName;
                    $usedSanitizedNames[] = $sanitizedName;
                }
            }
            
            if (rand(0, 10) > 1) { // 90% chance to include color
                $algo['color'] = $this->generateRandomColor();
            }
            
            // Only add if it has at least a name
            if (isset($algo['name'])) {
                $algos[] = $algo;
            }
        }
        
        return $algos;
    }
    
    /**
     * Generate random algorithm name
     * 
     * @return string
     */
    protected function generateRandomAlgoName()
    {
        $types = [
            // Standard algorithm names
            function() { return 'sha256'; },
            function() { return 'scrypt'; },
            function() { return 'x11'; },
            function() { return 'equihash'; },
            function() { return 'kawpow'; },
            // Names with special characters
            function() { return 'yespower_ARWN'; },
            function() { return 'SHA-256'; },
            function() { return 'x11-gost'; },
            function() { return 'yespower ARWN'; },
            // Edge cases
            function() { return 'a'; },
            function() { return 'algo123'; },
            function() { return 'test_algo_name'; },
            function() { return 'UPPERCASE'; },
            function() { return 'MixedCase'; },
        ];
        
        $generator = $types[array_rand($types)];
        return $generator();
    }
    
    /**
     * Generate random color value
     * 
     * @return string
     */
    protected function generateRandomColor()
    {
        $types = [
            // Valid hex colors (6 digits)
            function() { return sprintf('#%06x', rand(0, 0xFFFFFF)); },
            // Valid hex colors (3 digits)
            function() { return sprintf('#%03x', rand(0, 0xFFF)); },
            // Specific valid colors
            function() { return '#ffcc00'; },
            function() { return '#00ccff'; },
            function() { return '#ff00cc'; },
            function() { return '#f00'; },
            function() { return '#0F0'; },
            // Invalid formats (should use fallback)
            function() { return 'invalid'; },
            function() { return 'rgb(255,0,0)'; },
            function() { return 'red'; },
            function() { return '#gggggg'; },
            function() { return '#12345'; }, // Wrong length
            function() { return 'ffffff'; }, // Missing #
        ];
        
        $generator = $types[array_rand($types)];
        return $generator();
    }
    
    /**
     * Test with real algorithm data from YiimpUtils
     * 
     * @test
     */
    public function testDynamicStyleCorrectnessWithRealData()
    {
        // Feature: csp-inline-styles-removal, Property 4: Dynamic style correctness (real data)
        
        // Get real algorithm list from YiimpUtils
        $yiimpUtils = new YiimpUtils();
        $algoList = $yiimpUtils->get_algo_list();
        
        if (empty($algoList)) {
            $this->markTestSkipped('No algorithm data available from database');
            return;
        }
        
        // Generate CSS variables
        $cssVars = DynamicStyleManager::generateAlgoColorVars($algoList);
        
        // Verify each algorithm has a corresponding CSS variable
        foreach ($algoList as $algo) {
            if (!isset($algo['name']) || !isset($algo['color'])) {
                continue;
            }
            
            $className = DynamicStyleManager::getAlgoColorClass($algo['name']);
            $sanitizedName = substr($className, strlen('algo-bg-'));
            
            // Check that the CSS variable exists
            $this->assertStringContainsString(
                "--algo-color-{$sanitizedName}:",
                $cssVars,
                "CSS variable for algorithm {$algo['name']} should exist"
            );
            
            // Extract and verify the color
            $pattern = "/--algo-color-{$sanitizedName}:\s*([^;]+);/";
            $this->assertMatchesRegularExpression(
                $pattern,
                $cssVars,
                "CSS variable for algorithm {$algo['name']} should have a color value"
            );
            
            if (preg_match($pattern, $cssVars, $matches)) {
                $generatedColor = trim($matches[1]);
                
                // Verify it's a valid hex color
                $this->assertMatchesRegularExpression(
                    '/^#([A-Fa-f0-9]{3}|[A-Fa-f0-9]{6})$/',
                    $generatedColor,
                    "Generated color for {$algo['name']} should be valid hex"
                );
            }
        }
        
        // Test renderDynamicStyles with real data
        $config = ['algos' => $algoList];
        $styleTag = DynamicStyleManager::renderDynamicStyles($config);
        
        $this->assertStringContainsString('<style>', $styleTag);
        $this->assertStringContainsString('</style>', $styleTag);
        $this->assertStringContainsString(':root {', $styleTag);
    }
    
    /**
     * Test chart height integration
     * 
     * @test
     */
    public function testChartHeightIntegration()
    {
        // Feature: csp-inline-styles-removal, Property 4: Dynamic style correctness (chart height)
        
        $iterations = 50;
        $failures = [];
        
        for ($i = 0; $i < $iterations; $i++) {
            try {
                $height = $this->generateRandomHeight();
                $config = ['chartHeight' => $height];
                
                $styleTag = DynamicStyleManager::renderDynamicStyles($config);
                
                if (is_numeric($height)) {
                    // Should generate a style tag with chart height
                    if (strpos($styleTag, '--chart-height-custom:') === false) {
                        $failures[] = [
                            'iteration' => $i,
                            'height' => $height,
                            'reason' => 'Chart height variable not found',
                            'output' => $styleTag
                        ];
                    }
                    
                    // Verify the height value
                    $expectedHeight = (int) $height;
                    if (strpos($styleTag, "--chart-height-custom: {$expectedHeight}px;") === false) {
                        $failures[] = [
                            'iteration' => $i,
                            'height' => $height,
                            'reason' => 'Chart height value incorrect',
                            'expected' => "--chart-height-custom: {$expectedHeight}px;",
                            'output' => $styleTag
                        ];
                    }
                } else {
                    // Non-numeric height should result in empty string
                    if (!empty($styleTag)) {
                        $failures[] = [
                            'iteration' => $i,
                            'height' => $height,
                            'reason' => 'Non-numeric height should produce empty output',
                            'output' => $styleTag
                        ];
                    }
                }
                
            } catch (\Exception $e) {
                $failures[] = [
                    'iteration' => $i,
                    'reason' => 'Test execution failed',
                    'message' => $e->getMessage()
                ];
            }
        }
        
        if (!empty($failures)) {
            $this->fail(
                "Chart height property test failed in " . count($failures) . " out of $iterations iterations:\n" .
                json_encode($failures, JSON_PRETTY_PRINT)
            );
        }
        
        $this->assertTrue(true, "Chart height property holds for all $iterations iterations");
    }
    
    /**
     * Generate random height value
     * 
     * @return mixed
     */
    protected function generateRandomHeight()
    {
        $types = [
            function() { return 240; },
            function() { return 200; },
            function() { return 160; },
            function() { return rand(100, 500); },
            function() { return 0; },
            function() { return -1; },
            function() { return 'invalid'; },
            function() { return null; },
            function() { return '240'; }, // String number
        ];
        
        $generator = $types[array_rand($types)];
        return $generator();
    }
}
