<?php
/**
 * Yiimp2 Dedicated System Configuration
 * Generated by generate-yiimp2-configs.sh
 * 
 * This configuration is for the Yiimp2 dedicated system running in Docker containers.
 * It uses a separate database (yiimp2) and is completely independent from legacy Yiimp.
 */

ini_set('date.timezone', 'UTC');

define('YAAMP_LOGS', '/var/log/yiimp2');
define('YAAMP_HTDOCS', '/var/www');
define('YAAMP_BIN', '/var/www/bin');

// Yiimp2 Dedicated Database Configuration
// Allow environment variables to override for dev/test environments
define('YAAMP_DBHOST', getenv('DB_HOST') ?: 'yiimp2-db');
define('YAAMP_DBNAME', getenv('DB_NAME') ?: 'yiimp2');
define('YAAMP_DBUSER', getenv('DB_USER') ?: 'yiimp2');
define('YAAMP_DBPASSWORD', getenv('DB_PASSWORD') ?: 'yiimp2');

// Cookie Validation Key - REQUIRED for security
// This key is used by Yii2 to validate cookies and prevent tampering
// Set via YIIMP_COOKIE_VALIDATION_KEY environment variable
// Generate with: openssl rand -hex 32
// IMPORTANT: Keep this secret and never commit it to version control
// If not set, a random key will be generated (not recommended for production)
// define('YIIMP_COOKIE_VALIDATION_KEY', 'your-secret-key-here');

// Memcache Configuration for Docker Compose
// Allow environment variable override for dev environment
define('YAAMP_MEMCACHE_HOST', getenv('MEMCACHED_HOST') ?: 'yiimp2-memcached');
define('YAAMP_MEMCACHE_PORT', 11211);

define('YAAMP_SITE_URL', 'localhost:8090');
define('YAAMP_STRATUM_URL', YAAMP_SITE_URL);
define('YAAMP_SITE_NAME', 'Yiimp2 Mining Pool');

define('YAAMP_PRODUCTION', false);

define('YIIMP_PUBLIC_EXPLORER', true);
define('YIIMP_PUBLIC_BENCHMARK', false);

// API Configuration
define('YIIMP_API_URL', YAAMP_SITE_URL); // Base URL for API documentation examples
define('YIIMP_API_PAYOUTS', false); // Enable/disable payout history in walletEx endpoint
define('YIIMP_API_PAYOUTS_PERIOD', 24*60*60); // Time period in seconds for payout history (default: 24 hours)

define('YAAMP_RENTAL', false);
define('YAAMP_LIMIT_ESTIMATE', false);

define('YAAMP_FEES_SOLO', 1);
define('YAAMP_FEES_MINING', 0.5);
define('YAAMP_FEES_EXCHANGE', 2);
define('YAAMP_FEES_RENTING', 2);
define('YAAMP_TXFEE_RENTING_WD', 0.002);
define('YAAMP_PAYMENTS_FREQ', 3*60*60);
define('YAAMP_PAYMENTS_MINI', 0.1);

define('YAAMP_ALLOW_EXCHANGE', false);
define('YIIMP_FIAT_ALTERNATIVE', 'EUR');

define('YAAMP_USE_NICEHASH_API', false);

define('YAAMP_BTCADDRESS', '');

define('YIIMP_ADMIN_LOGIN', true);
define('YAAMP_ADMIN_EMAIL', 'admin@localhost');
define('YAAMP_ADMIN_USER', 'admin');
define('YAAMP_ADMIN_PASS', 'changeme');
define('YAAMP_ADMIN_IP', '127.0.0.1');
define('YAAMP_ADMIN_WEBCONSOLE', true);
define('YAAMP_CREATE_NEW_COINS', false);
define('YAAMP_NOTIFY_NEW_COINS', false);
define('YAAMP_DEFAULT_ALGO', 'sha256');

define('GITHUB_ACCESSTOKEN', '');

define('SMTP_HOST', '');
define('SMTP_PORT', 25);
define('SMTP_USEAUTH', false);
define('SMTP_USERNAME', '');
define('SMTP_PASSWORD', '');
define('SMTP_DEFAULT_FROM', '');
define('SMTP_DEFAULT_HELO', '');

define('YAAMP_USE_NGINX', false);

define('YIIMP_MYSQLDUMP_USER', 'yiimp2');
define('YIIMP_MYSQLDUMP_PASS', 'yiimp2');

// Exchange keys (empty for dedicated system)
define('EXCH_BINANCE_KEY', '');
define('EXCH_BINANCE_SECRET', '');
define('EXCH_CEXIO_SECRET', '');
define('EXCH_EXBITRON_KEY', '');
define('EXCH_HITBTC_SECRET', '');
define('EXCH_HITBTC_KEY','');
define('EXCH_KRAKEN_KEY', '');
define('EXCH_KRAKEN_SECRET','');
define('EXCH_KUCOIN_SECRET', '');
define('EXCH_POLONIEX_KEY', '');
define('EXCH_POLONIEX_SECRET', '');
define('EXCH_SAFETRADE_KEY', '');
define('EXCH_SAFETRADE_SECRET', '');
define('EXCH_TRADEOGRE_KEY', '');
define('EXCH_TRADEOGRE_SECRET', '');
define('EXCH_YOBIT_KEY', '');
define('EXCH_YOBIT_SECRET', '');
define('EXCH_NONKYC_KEY', '');
define('EXCH_NONKYC_SECRET', '');
define('EXCH_XEGGEX_KEY', '');
define('EXCH_XEGGEX_SECRET', '');

define('EXCH_AUTO_WITHDRAW', 0);

define('NICEHASH_API_KEY','');
define('NICEHASH_API_ID','');
define('NICEHASH_DEPOSIT','');
define('NICEHASH_DEPOSIT_AMOUNT','0');

$cold_wallet_table = array();

$configFixedPoolFees = array();
$configFixedPoolFeesSolo = array();
$configCustomPorts = array();
$configAlgoNormCoef = array();

